import type { Metadata } from "next";
import "./globals.css";
import StyledComponentsRegistry from "./lib/registry";
import { Bad_Script, Chau_Philomene_One, Ubuntu } from 'next/font/google';
import NavBar from "./components/navbar/Navbar";

const fontMain = Ubuntu({ 
  subsets: ["latin"],
  weight:  ['400','500'],
  variable: '--font-main',
  display: 'swap',
});

const fontSecondary = Bad_Script({ 
  subsets: ["latin"],
  weight: '400',
  variable: '--font-secondary',
  display: 'swap',
});

const fontHeader = Chau_Philomene_One({
  subsets: ["latin"],
  weight: '400',
  variable: '--font-header',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontMain.variable} ${fontSecondary.variable} ${fontHeader.variable}`}>
        <StyledComponentsRegistry>
          <NavBar />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
